// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn4fCjDuHqbQQVWDk1-dgwqfsO7NieIq0',
    appId: '1:814543443819:web:0b95e8f2f3eea54cd41e2e',
    messagingSenderId: '814543443819',
    projectId: 'eagle-investment',
    authDomain: 'eagle-investment.firebaseapp.com',
    storageBucket: 'eagle-investment.appspot.com',
    measurementId: 'G-HCC4WDLMD9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRj2uaLS_sHe9mMsb659lS6y0IU8RlBPI',
    appId: '1:814543443819:android:e24f1727647404b2d41e2e',
    messagingSenderId: '814543443819',
    projectId: 'eagle-investment',
    storageBucket: 'eagle-investment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwwNntZIHl11XBTZNnHD3vZxmYi1fCVeU',
    appId: '1:814543443819:ios:fa1998f3d1695097d41e2e',
    messagingSenderId: '814543443819',
    projectId: 'eagle-investment',
    storageBucket: 'eagle-investment.appspot.com',
    androidClientId: '814543443819-02e9tvdp55bmhaq15n7q7lbr1d4p19lo.apps.googleusercontent.com',
    iosClientId: '814543443819-d4pi5saa9igma4vphhsfhv6pkpui4mam.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwwNntZIHl11XBTZNnHD3vZxmYi1fCVeU',
    appId: '1:814543443819:ios:fa1998f3d1695097d41e2e',
    messagingSenderId: '814543443819',
    projectId: 'eagle-investment',
    storageBucket: 'eagle-investment.appspot.com',
    androidClientId: '814543443819-02e9tvdp55bmhaq15n7q7lbr1d4p19lo.apps.googleusercontent.com',
    iosClientId: '814543443819-d4pi5saa9igma4vphhsfhv6pkpui4mam.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled8',
  );
}
